name: asap-admet
channels:
  - conda-forge
dependencies:
  - datamol
  - fsspec
  - matplotlib
  - notebook
  - numpy
  - pandas>=2.1.2,<=2.2.3
  - pip
  - python=3.11
  - scikit-learn>=1.3.1,<=1.6.1
  - scipy
  - seaborn
#  - pip:
#      - tabpfn-client==0.1.4
